import type { Metadata } from "next";
import { Jura } from "next/font/google";
import "./globals.css";
import React from "react";
import type { AppProps } from 'next/app'
import { Header } from "@/components/header";

const jura = Jura({
  variable: "--font-jura-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  { children, }: Readonly<{ children: React.ReactNode; }>
) {
  return (
    <>
      <html lang="en">
        <body className={`${jura.variable} font-sans antialiased`}>
          <Header></Header>
          {children}
        </body>
      </html>
    </>

  );
}
